name: kinbo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_storage: ^12.4.2
  flutter_cache_manager: ^3.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.3
  image: ^4.1.7
  image_picker: ^1.0.7
  location: ^8.0.0
  #paginate_firestore: ^1.0.3
  provider: ^6.1.2
  intl: ^0.18.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon.jpg"
  min_sdk_android: 23 # android min sdk min:16, default 21